using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

namespace Blobby.UserInterface
{
    public static class BlobbyKey
    {
        public static Dictionary<KeyCode, string> KeyToName = new Dictionary<KeyCode, string>
        {
            {KeyCode.Alpha0, "0"},
            {KeyCode.Alpha1, "1"},
            {KeyCode.Alpha2, "2"},
            {KeyCode.Alpha3, "3"},
            {KeyCode.Alpha4, "4"},
            {KeyCode.Alpha5, "5"},
            {KeyCode.Alpha6, "6"},
            {KeyCode.Alpha7, "7"},
            {KeyCode.Alpha8, "8"},
            {KeyCode.Alpha9, "9"},
            {KeyCode.Keypad0, "Num 0"},
            {KeyCode.Keypad1, "Num 1"},
            {KeyCode.Keypad2, "Num 2"},
            {KeyCode.Keypad3, "Num 3"},
            {KeyCode.Keypad4, "Num 4"},
            {KeyCode.Keypad5, "Num 5"},
            {KeyCode.Keypad6, "Num 6"},
            {KeyCode.Keypad7, "Num 7"},
            {KeyCode.Keypad8, "Num 8"},
            {KeyCode.Keypad9, "Num 9"},
            {KeyCode.A, "A"},
            {KeyCode.B, "B"},
            {KeyCode.C, "C"},
            {KeyCode.D, "D"},
            {KeyCode.E, "E"},
            {KeyCode.F, "F"},
            {KeyCode.G, "G"},
            {KeyCode.H, "H"},
            {KeyCode.I, "I"},
            {KeyCode.J, "J"},
            {KeyCode.K, "K"},
            {KeyCode.L, "L"},
            {KeyCode.M, "M"},
            {KeyCode.N, "N"},
            {KeyCode.O, "O"},
            {KeyCode.P, "P"},
            {KeyCode.Q, "Q"},
            {KeyCode.R, "R"},
            {KeyCode.S, "S"},
            {KeyCode.T, "T"},
            {KeyCode.U, "U"},
            {KeyCode.V, "V"},
            {KeyCode.W, "W"},
            {KeyCode.X, "X"},
            {KeyCode.Y, "Y"},
            {KeyCode.Z, "Z"},
            {KeyCode.Quote, "Ä"},
            {KeyCode.LeftBracket, "ß"},
            {KeyCode.BackQuote, "Ö"},
            {KeyCode.Space, "Space"},
            {KeyCode.Minus, "-"},
            {KeyCode.RightBracket, "´"},
            {KeyCode.Backslash, "^"},
            {KeyCode.Comma, ","},
            {KeyCode.Period, "."},
            {KeyCode.Slash, "#"},
            {KeyCode.KeypadDivide, "Num /"},
            {KeyCode.KeypadMultiply, "Num *"},
            {KeyCode.KeypadMinus, "Num -"},
            {KeyCode.KeypadPlus, "Num +"},
            {KeyCode.KeypadPeriod, "Num ,"},
            {KeyCode.UpArrow, "Up"},
            {KeyCode.LeftArrow, "Left"},
            {KeyCode.DownArrow, "Down"},
            {KeyCode.RightArrow, "Right"},
        };
    }
}