name: deploy-client

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Testing
    runs-on: self-hosted
    steps:

      - name: Checking out
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Caching Library
        uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-blobby-volley-client-StandaloneWindows64
          restore-keys: |
            Library-blobby-volley-client-
            Library-

      - name: Running unit tests
        uses: game-ci/unity-test-runner@v2.0-alpha-2
        with:
          artifactsPath: ./deploy-client-test-results/

      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./deploy-client-test-results/

  build:
    name: Building
    needs: test
    runs-on: self-hosted
    steps:
    
      - name: Checking out
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-blobby-volley-client-StandaloneWindows64
          restore-keys: |
            Library-blobby-volley-client-
            Library-
      
      - name: Building client
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          targetPlatform: StandaloneWindows64
          buildsPath: ./deploy-client-builds/
          buildMethod: "Editor.Builder.BuildClient"
          buildName: "blobby-volley-world-windows"
      
      - name: Uploading to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: blobby-volley-world-windows
          ITCH_GAME: blobby-volley-world
          ITCH_USER: EuleMitKeule
          PACKAGE: ./deploy-client-builds/blobby-volley-world-windows/
