name: deploy-client

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Testing
    runs-on: self-hosted
    steps:

      - name: Checking out
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Caching Library
        uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-blobby-volley-world-StandaloneLinux64

      - name: Running unit tests
        uses: game-ci/unity-test-runner@v2.0-alpha-2
        with:
          artifactsPath: ./deploy-client-test-results/

      - name: Uploading results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./deploy-client-test-results/

      - name: Storing results
        run: |
          mkdir -p ../test-results/client/temp
          mv ./deploy-client-test-results/* ../test-results/client/temp

  build:
    name: Building
    needs: test
    runs-on: self-hosted
    steps:
    
      - name: Checking out
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Caching Library
        uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-blobby-volley-world-StandaloneLinux64
      
      - name: Building Client
        uses: game-ci/unity-builder@v2.0-alpha-6
        id: build
        with:
          targetPlatform: StandaloneLinux64
          buildsPath: ./deploy-client-builds/
          buildMethod: "Editor.Builder.BuildClient"
          buildName: "blobby-volley-world"
          versioning: Semantic
      
      - name: Uploading to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: blobby-volley-world
          ITCH_USER: EuleMitKeule
          PACKAGE: ./deploy-client-builds/StandaloneLinux64/
          VERSION: ${{ steps.build.outputs.buildVersion }}

      - name: Storing build
        run: |
          mkdir -p ../builds/client/linux/${{ steps.build.outputs.buildVersion }}/
          mkdir -p ../test-results/client/${{ steps.build.outputs.buildVersion }}/
          mv ./deploy-client-builds/StandaloneLinux64/* ../builds/client/linux/${{ steps.build.outputs.buildVersion }}/

      - name: Moving test-results
        run: |
          mv ../test-results/client/temp/* ../test-results/client/${{ steps.build.outputs.buildVersion }}/

      - name: Zipping build
        uses: papeloto/action-zip@v1
        with:
          files: ../builds/client/linux/${{ steps.build.outputs.buildVersion }}/
          dest: ../builds/client/linux/${{ steps.build.outputs.buildVersion }}.zip

      - name: Cleanup
        run: |
          rm -r ../builds/client/linux/${{ steps.build.outputs.buildVersion }}/
          mkdir -p ../builds/client/linux/${{ steps.build.outputs.buildVersion }}/
          mv ../builds/client/linux/${{ steps.build.outputs.buildVersion }}.zip ../builds/client/linux/${{ steps.build.outputs.buildVersion }}/${{ steps.build.outputs.buildVersion }}.zip
          rm -r ../test-results/client/temp/