# This workflow should build the game client and publish it to itch.io

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # manual activation of workflow allowed
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build Blobby Volley Client
    runs-on: self-hosted
    steps:
      # checks out repo to $GITHUB_WORKSPACE
      - name: Checking out
        uses: actions/checkout@v2
      
      # enables caching for faster build process 
      #- name: Caching
      #  uses: actions/cache@v1.1.0
      #  with:
      #    path: Library
      #    key: Library- uses: actions/cache@v1.1.0
      - uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-blobby-volley-client-StandaloneWindows64
          restore-keys: |
            Library-blobby-volley-client-
            Library-
      
      # runs Unity test
      
      # builds Unity project
      - name: Building
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          unityVersion: 2020.2.2f1
          targetPlatform: StandaloneWindows64
          buildMethod: 'Editor.Build.BuildClient'
          
      # output artifact
      #- name: Outputting
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: Build
      #    path: build
      
      # upload build to itch.io
      # - name: Uploading
      #   uses: josephbmanley/butler-publish-itchio-action@master
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      #     CHANNEL: windows
      #     ITCH_GAME: blobby-volley-world
      #     ITCH_USER: EuleMitKeule
      #     PACKAGE: build
