# This workflow should build the game client and publish it to itch.io

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # manual activation of workflow allowed
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build Blobby Volley Client
    runs-on: ubuntu-latest
    steps:
      # checks out repo to $GITHUB_WORKSPACE
      - name: Checking out
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # enables caching for faster build process 
      - name: Caching
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      
      # runs Unity test
      
      # builds Unity project
      - name: Building
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2020.2.2f1
          targetPlatform: StandaloneWindows64
          
      # output artifact (later itch.io)
      - name: Outputting
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
