name: pr-test-client

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Testing
    runs-on: self-hosted
    steps:

      - name: Checking out
        uses: actions/checkout@v2.1.4
        with:
          lfs: true

      - name: Caching Library
        uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-blobby-volley-client-StandaloneWindows64
          restore-keys: |
            Library-blobby-volley-client-
            Library-

      - name: Running unit tests
        uses: game-ci/unity-test-runner@v2.0-alpha-2
        with:
          artifacts-path: ./ci/pr-test-client/test-results/

  build:
    name: Building
    runs-on: self-hosted
    steps:
    
      - name: Checking out
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-blobby-volley-client-StandaloneWindows64
          restore-keys: |
            Library-blobby-volley-client-
            Library-
      
      - name: Building client
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          targetPlatform: StandaloneWindows64
          buildsPath: ./ci/pr-test-client/build/
          buildMethod: "BlobbyEditor.Builder.BuildClient"
