name: pr-test-server

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:

  build:
    name: Building
    runs-on: self-hosted
    steps:
    
      - name: Checking out
        uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Caching Library
        uses: actions/cache@v2.1.4
        with:
          path: Library
          key: Library-blobby-volley-client-StandaloneWindows64
          restore-keys: |
            Library-blobby-volley-client-
            Library-
      
      - name: Building server
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          targetPlatform: StandaloneLinux64
          buildsPath: ./pr-test-server-builds/
          buildMethod: "Editor.Builder.BuildServer"
          buildName: blobby-volley-world-server-linux
