name: return-license

on: 
  workflow_dispatch:

jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
          
      - name: Unity - Return License
        uses: game-ci/unity-return-license@v1.1
